# LLM configuration for video generation
version: 1.0

# Model settings
model:
  name: "gpt-4-turbo-preview"  # Default model to use
  temperature: 0.7           # Creativity level
  max_tokens: 2000          # Maximum tokens per request
  presence_penalty: 0.0     # Presence penalty
  frequency_penalty: 0.0    # Frequency penalty

# Script generation
script:
  system_prompt: |
    You are a professional real estate video script writer.
    Create engaging, natural-sounding scripts that highlight
    property features and appeal to potential buyers.
  max_length: 500          # Maximum script length in words
  style_tags:              # Available style tags
    - modern
    - luxury
    - cozy
    - professional
    - casual

# Prompt templates
templates:
  script_generation: |
    Create a video script for the following property:
    {property_details}
    
    Style: {style}
    Target Duration: {duration} seconds
    
    Focus on these key features:
    {key_features}

# Safety
safety:
  content_filter: true     # Enable content filtering
  max_retries: 3          # Maximum retries for failed generations
